# config for travis-ci
language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"  
install:
  # gcut version
  - "pip install -v -e ."
script: true
addons:
  apt:
    packages:
    - build-essential    
    - libboost-python-dev
cache:
- apt
- directories:
  - "$HOME/.cache/pip"
