# config for travis-ci
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_install:
  - "sudo apt-get install libopenblas-base libatlas3-base libgfortran build-essential"
  - "sudo apt-get install libumfpack5.4.0"
install:
  # non gcut version
  - "sudo pip install ."
  # gcut version
  #- "apt-get install libboost-python-dev"
  #- "pip install ."
