# config for travis-ci
language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"  
install:
  # gcut version
  - "pip install -v -e ."
script: true
cache:
- directories:
  - "$HOME/.cache/pip"
